spring:
  application:
    name: order-service
  zipkin:
    base-url: http://localhost:9411/

server:
  port: 8282
eureka:
  instance:
    hostname: localhost
    serviceUrl:
      defaultZone : http://${eureka.instance.hostname}:8761/eureka/

security:
  oauth2:
    resource:
      token-info-uri: http://authentication-service/oauth/check_token
    client:
      client-id: javadeveloperzone
      client-secret: secret

feign:
  circuitbreaker:
    enabled: true